
ptBinning: [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 999.0]

LHC17p: 
    0_100: [0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97]
LHC17q: 
    0_100: [0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97]

LHC18q: 
    0_10: [0.964, 0.964 , 0.939 , 0.936 , 0.949 , 0.958 , 0.976 , 0.967 , 0.967 , 0.967 , 0.967 , 0.976 , 0.976 , 0.984 , 0.976 , 0.976]
    30_50: [0.966, 0.966 , 0.958 , 0.958 , 0.958 , 0.967 , 0.976 , 0.984 , 0.984 , 0.983 , 0.983 , 0.983 , 0.983 , 0.983 , 0.983, 0.983]
LHC18r:
    0_10: [0.963, 0.963 , 0.940 , 0.936 , 0.949 , 0.958 , 0.977 , 0.967 , 0.976 , 0.966 , 0.975 , 0.975 , 0.975 , 0.982 , 0.982, 0.982] 
    30_50: [0.965, 0.965 , 0.958 , 0.956 , 0.959 , 0.967 , 0.986 , 0.978 , 0.986 , 0.978 , 0.986 , 0.986 , 0.986 , 0.986 , 0.986 , 0.986]
