configurationName: "EMCal correction framework configuration for multiple xTalk and V3 clusters"
pass: "pass1"

inputObjects:
    cells:
        cells:
            branchName: "usedefault"
        cells_xTalkOff:
            branchName: "cells_xTalkOff"
        cells_xTalk:
            branchName: "cells_xTalk"
        cells_xTalkMore:
            branchName: "cells_xTalkMore"
        cells_xTalkLess:
            branchName: "cells_xTalkLess"
        cells_xTalkMoreCenEta:
            branchName: "cells_xTalkMoreCenEta"
    clusterContainers:
        baseClusterContainer:
            branchName: "V1clusters_xTalkOff"
        baseClusterContainer_xTalk:
            branchName: "V1clusters_xTalk"
        baseClusterContainer_xTalkMore:
            branchName: "V1clusters_xTalkMore"
        baseClusterContainer_xTalkLess:
            branchName: "V1clusters_xTalkLess"
        baseClusterContainer_xTalkMoreCenEta:
            branchName: "V1clusters_xTalkMoreCenEta"
       
# Clone cells branch
CellCloneContainer:
    cellsNames:
      - cells
CellCloneContainer_xTalkOff:
    enabled: true        
    clonedCellsBranchName: "cells_xTalkOff"
CellCloneContainer_xTalk:
    enabled: true        
    clonedCellsBranchName: "cells_xTalk"
CellCloneContainer_xTalkMore:
    enabled: true        
    clonedCellsBranchName: "cells_xTalkMore"
CellCloneContainer_xTalkLess:
    enabled: true        
    clonedCellsBranchName: "cells_xTalkLess"
CellCloneContainer_xTalkMoreCenEta:
    enabled: true
    clonedCellsBranchName: "cells_xTalkMoreCenEta"
        
# Cross talk emulation   
CellEmulateCrosstalk:   
    createHistos: true
    inducedTCardMinimum: 0.1  
    inducedEnergyLossFraction:                      # Fraction of energy lost by max energy cell in one of T-Card cells
        enabled: true                               # Enable setting these values
        values: {0 : [1.15e-02, 1.15e-02, 1.15e-02, 0], 
                 1 : [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 2 : [1.15e-02, 1.15e-02, 1.15e-02, 0], 
                 3 : [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 4 : [1.15e-02, 1.15e-02, 1.15e-02, 0],  
                 5 : [1.15e-02, 1.15e-02, 1.15e-02, 0],  
                 6 : [1.15e-02, 1.15e-02, 1.15e-02, 0],  
                 7 : [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 8 : [0.80e-02, 0.80e-02, 0.80e-02, 0],  
                 9 : [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 10: [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 11: [1.15e-02, 1.15e-02, 1.15e-02, 0], 
                 12: [1.15e-02, 1.15e-02, 1.15e-02, 0], 
                 13: [1.15e-02, 1.15e-02, 1.15e-02, 0],  
                 14: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 15: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 16: [1.15e-02, 1.15e-02, 1.15e-02, 0],  
                 17: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 18: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 19: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 20: [0.80e-02, 0.80e-02, 0.80e-02, 0],
                 21: [0.80e-02, 0.80e-02, 0.80e-02, 0]} 
CellEmulateCrosstalk_xTalkOff:                 
    enabled: false                            
    cellsNames:
        - cells_xTalkOff
CellEmulateCrosstalk_xTalk:                  
    enabled: true                              
    inducedEnergyLossMinimumFraction:               
        enabled: true
        inducedEnergyLossMinimumFraction:           # Minimum induced energy fraction when linear dependency is set
        enabled: true                               # Enable setting these values
        values: {0 : [4.5e-3], 1 : [5.0e-3], 2 : [4.5e-3], 3 : [6.0e-3], 4 : [4.5e-3], 5 : [4.5e-3], 
                 6 : [4.5e-3], 7 : [6.0e-3], 8 : [3.5e-3], 9 : [3.5e-3], 10: [5.0e-3], 11: [4.5e-3], 
                 12: [4.5e-3], 13: [4.5e-3], 14: [3.5e-3], 15: [3.5e-3], 16: [4.5e-3], 17: [3.5e-3], 
                 18: [3.5e-3], 19: [3.5e-3], 20: [3.5e-3], 21: [3.5e-3]} 
    cellsNames:
        - cells_xTalk
CellEmulateCrosstalk_xTalkMore:                 
    enabled: true                              
    inducedEnergyLossMinimumFraction:               
        enabled: true     
        values: {0 : [6.8e-3], 1 : [7.5e-3], 2 : [6.8e-3], 3 : [9.0e-3], 4 : [6.8e-3], 5 : [6.8e-3], 
                 6 : [6.8e-3], 7 : [9.0e-3], 8 : [5.2e-3], 9 : [5.2e-3], 10: [7.5e-3], 11: [6.8e-3], 
                 12: [6.8e-3], 13: [6.8e-3], 14: [5.2e-3], 15: [5.2e-3], 16: [6.8e-3], 17: [5.2e-3], 
                 18: [5.2e-3], 19: [5.2e-3], 20: [5.2e-3], 21: [5.2e-3]} 
    cellsNames:
        - cells_xTalkMore
CellEmulateCrosstalk_xTalkLess:                 
    enabled: true                              
    inducedEnergyLossMinimumFraction:               
        enabled: true          
        values: {0 : [2.35e-3], 1 : [2.5e-3] , 2 : [2.35e-3], 3 : [3.0e-3] , 4 : [2.35e-3], 5 : [2.35e-3], 
                 6 : [2.35e-3], 7 : [2.35e-3], 8 : [1.75e-3], 9 : [1.75e-3], 10: [2.5e-3] , 11: [2.35e-3], 
                 12: [2.35e-3], 13: [2.35e-3], 14: [1.75e-3], 15: [1.75e-3], 16: [2.35e-3], 17: [1.75e-3], 
                 18: [1.75e-3], 19: [1.75e-3], 20: [1.75e-3], 21: [1.75e-3]} 
    cellsNames:
        - cells_xTalkLess
CellEmulateCrosstalk_xTalkMoreCenEta:
    enabled: true
     inducedEnergyLossMinimumFraction:
        enabled: true
        values: {0 : [4.5e-3], 1 : [5.0e-3], 2 : [4.5e-3], 3 : [6.0e-3], 4 : [2.0e-3], 5 : [2.0e-3],
                 6 : [4.5e-3], 7 : [6.0e-3], 8 : [3.5e-3], 9 : [3.5e-3], 10: [2.5e-3], 11: [2.5e-3],
                 12: [4.5e-3], 13: [4.5e-3], 14: [3.5e-3], 15: [3.5e-3], 16: [4.5e-3], 17: [3.5e-3],
                 18: [3.5e-3], 19: [3.5e-3], 20: [3.5e-3], 21: [3.5e-3]}
     inducedEnergyLossMinimumFractionCentralEta:
        enabled: true
        values: {0 : [6.8e-3], 1 : [7.5e-3], 2 : [6.8e-3], 3 : [9.0e-3], 4 : [4.5e-3], 5 : [4.5e-3],
                 6 : [6.8e-3], 7 : [9.0e-3], 8 : [5.2e-3], 9 : [5.2e-3], 10: [5.0e-3], 11: [5.0e-3],
                 12: [6.8e-3], 13: [6.8e-3], 14: [5.2e-3], 15: [5.2e-3], 16: [6.8e-3], 17: [5.2e-3],
                 18: [6.8e-3], 19: [6.8e-3], 20: [5.2e-3], 21: [5.2e-3]}
    cellsNames:
        - cells_xTalkMoreCenEta
   
# Cell bad channel
CellBadChannel:
    createHistos: true
CellBadChannel_xTalkOff:
    enabled: true
    cellsNames:
        - cells_xTalkOff
CellBadChannel_xTalk:
    enabled: true
    cellsNames:
        - cells_xTalk
CellBadChannel_xTalkMore:
    enabled: true
    cellsNames:
        - cells_xTalkMore
CellBadChannel_xTalkLess:
    enabled: true
    cellsNames:
        - cells_xTalkLess
CellBadChannel_xTalkMoreCenEta:
    enabled: true
    cellsNames:
        - cells_xTalkMoreCenEta
    
# Cell Energy Calib
CellEnergy:
    enabled: false

# Cell Time Calib
CellTimeCalib:
    enabled: false        

# Clusterizer
Clusterizer:
    createHistos: true
    clusterizer: kClusterizerv3
    cellE: 0.1
    seedE: 0.5
    cellTimeMin: -500e-6
    cellTimeMax:  500e-6
    clusterTimeLength: 1e6
    recalDistToBadChannels: true                    
    recalShowerShape: false                         
    setCellMCLabelFromCluster: 0
    enableFracEMCRecalc: true     # false on old productions
    remapMcAod: false             # true on old productions
Clusterizer_xTalkOff:
    enabled: true
    cellsNames:
        - cells_xTalkOff
    clusterContainersNames:
        - baseClusterContainer_xTalkOff
Clusterizer_xTalk:
    enabled: true
    cellsNames:
        - cells_xTalk
    clusterContainersNames:
        - baseClusterContainer_xTalk
Clusterizer_xTalkMore:
    enabled: true
    cellsNames:
        - cells_xTalkMore
    clusterContainersNames:
        - baseClusterContainer_xTalkMore
Clusterizer_xTalkLess:
    enabled: true
    cellsNames:
        - cells_xTalkLess
    clusterContainersNames:
        - baseClusterContainer_xTalkLess
Clusterizer_xTalkMoreCenEta:
    enabled: true
    cellsNames:
        - cells_xTalkMoreCenEta
    clusterContainersNames:
        - baseClusterContainer_xTalkMoreCenEta
    
# Non-linearity
ClusterNonLinearity:
    setForceClusterE: true
    createHistos: true
    nonLinFunct: kTestBeamFinalMC  
ClusterNonLinearity_xTalkOff:
    enabled: true
    cellsNames:
        - cells_xTalkOff
    clusterContainersNames:
        - baseClusterContainer_xTalkOff
ClusterNonLinearity_xTalk:
    enabled: true
    cellsNames:
        - cells_xTalk
    clusterContainersNames:
        - baseClusterContainer_xTalk        
ClusterNonLinearity_xTalkMore:
    enabled: true
    cellsNames:
        - cells_xTalkMore
    clusterContainersNames:
        - baseClusterContainer_xTalkMore
ClusterNonLinearity_xTalkLess:
    enabled: true
    cellsNames:
        - cells_xTalkLess
    clusterContainersNames:
        - baseClusterContainer_xTalkLess
ClusterNonLinearity_xTalkMoreCenEta:
    enabled: true
    cellsNames:
        - cells_xTalkMoreCenEta
    clusterContainersNames:
        - baseClusterContainer_xTalkMoreCenEta

# Non-linearity after burner
ClusterNonLinearityMCAfterburner:
    afterburnerVersion: kPCM_EMCal
    setForceClusterE: true
    createHistos: true
    setMCPeriod: "kTestBeamFinalMCRun2"
ClusterNonLinearityMCAfterburner_xTalkOff:
    enabled: true
    cellsNames:
        - cells_xTalkOff
    clusterContainersNames:
        - baseClusterContainer_xTalkOff
ClusterNonLinearityMCAfterburner_xTalk:
    enabled: true
    cellsNames:
        - cells_xTalk
    clusterContainersNames:
        - baseClusterContainer_xTalk
ClusterNonLinearityMCAfterburner_xTalkMore:
    enabled: true
    cellsNames:
        - cells_xTalkMore
    clusterContainersNames:
        - baseClusterContainer_xTalkMore
ClusterNonLinearityMCAfterburner_xTalkLess:
    enabled: true
    cellsNames:
        - cells_xTalkLess
    clusterContainersNames:
        - baseClusterContainer_xTalkLess
ClusterNonLinearityMCAfterburner_xTalkMoreCenEta:
    enabled: true
    cellsNames:
        - cells_xTalkMoreCenEta
    clusterContainersNames:
        - baseClusterContainer_xTalkMoreCenEta
    
# Cluster-track matcher
ClusterTrackMatcher:
    createHistos: true
ClusterTrackMatcher_xTalkOff:
    enabled: true
    clusterContainersNames:
        - baseClusterContainer_xTalkOff
ClusterTrackMatcher_xTalk:
    enabled: true
    clusterContainersNames:
        - baseClusterContainer_xTalk
ClusterTrackMatcher_xTalkMore:
    enabled: true
    clusterContainersNames:
        - baseClusterContainer_xTalkMore    
ClusterTrackMatcher_xTalkLess:
    enabled: true
    clusterContainersNames:
        - baseClusterContainer_xTalkLess  
ClusterTrackMatcher_xTalkMoreCenEta:
    enabled: true
    clusterContainersNames:
        - baseClusterContainer_xTalkMoreCenEta
