configurationName: "EMCal Data Correction Cluster V2, Run2 T corrections"

CellEnergy:
    enabled: true
    createHistos: true
    enableNewTempCalib: true
CellBadChannel:
    enabled: true
    createHistos: true
CellTimeCalib:
    enabled: true
    createHistos: true
Clusterizer:
    enabled: true
    clusterizer: kClusterizerv2
    cellE: 0.1
    seedE: 0.5
    cellTimeMin: -50e-6
    cellTimeMax:  50e-6
    clusterTimeLength: 1e6
    createHistos: true
    recalDistToBadChannels: true
    recalShowerShape: false
ClusterExotics:
    enabled: true
    createHistos: true
ClusterNonLinearity:
    enabled: true
    setForceClusterE: true
    createHistos: true
    nonLinFunct: kBeamTestCorrectedv3
ClusterTrackMatcher:
    enabled: true
    createHistos: true
