configurationName: "EMCal MC Correction Cluster V1 Run1 with cross talk emulation"
pass: "pass1"
CellEnergy:
    enabled: false
    createHistos: false
CellBadChannel:
    enabled: true
    createHistos: true
CellTimeCalib:
    enabled: false
    createHistos: false
Clusterizer:
    enabled: true
    clusterizer: kClusterizerv1
    cellE: 0.1
    seedE: 0.5
    cellTimeMin: -50e-6
    cellTimeMax:  50e-6
    clusterTimeLength: 1e6
    createHistos: true
    recalDistToBadChannels: true
    recalShowerShape: false
    remapMcAod: true
    setCellMCLabelFromCluster: 0                    # use 2 if V1 and E cell 50 MeV
ClusterExotics:
    enabled: true
    createHistos: true
ClusterNonLinearity:
    enabled: true
    setForceClusterE: true
    createHistos: true
    nonLinFunct: kPi0MCv3
ClusterTrackMatcher:
    enabled: true
    createHistos: true
CellEmulateCrosstalk:                               # Component to emulate crosstalk
    enabled: true                                   # Whether to enable the task
    createHistos: true                              # Whether the task should create output histograms
    printConfiguration: true                        # Print the configuration after initialization
    conservEnergy: true                             # Activate cluster energy conservation
    randomizeTCardInducedEnergy: true               # Randomize the energy fraction induced by the TCard
    inducedTCardMinimumCellEnergy: 0.01             # Minimum cell energy induced by the TCard
    inducedTCardMaximum: 100                        # Maximum energy induced by the TCard
    inducedTCardMinimum: 0.0                        # Minimum energy induced by the TCard + cell energy, IMPORTANT use the same value as the clusterization cell E threshold or not too far from it
    inducedTCardMaximumELeak: 0                     # Maximum energy that is going to be leaked independently of what is set with inducedTCardMinimum    
    inducedEnergyLossConstant:                      # Constant energy lost by max energy cell in one of T-Card cells
        enabled: false                              # Enable setting these values
        values: {"all" : [0.02, 0.02, 0.02, 0]}     # Values are energy lost in [ upper/lower cell in same column, upper/lower cell in left or right, left or right cell in same row, 2nd row upper/lower cells]
    inducedEnergyLossFraction:                      # Fraction of energy lost by max energy cell in one of T-Card cells
        enabled: true                               # Enable setting these values
       #values: {"all" : [0.02, 0.02, 0.02, 0]}     # Values are energy lost in [ upper/lower cell in same column, upper/lower cell in left or right, left or right cell in same row, 2nd row upper/lower cells]
        values: {0 : [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 1 : [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 2 : [1.15e-02, 1.15e-02, 1.15e-02, 0], 
                 3 : [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 4 : [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 5 : [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 6 : [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 7 : [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 8 : [0.80e-02, 0.80e-02, 0.80e-02, 0],  
                 9 : [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 10: [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 11: [1.20e-02, 1.20e-02, 1.20e-02, 0], 
                 12: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 13: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 14: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 15: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 16: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 17: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 18: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 19: [0.80e-02, 0.80e-02, 0.80e-02, 0], 
                 20: [0.80e-02, 0.80e-02, 0.80e-02, 0],
                 21: [0.80e-02, 0.80e-02, 0.80e-02, 0]} 
    inducedEnergyLossFractionP1:                    # Slope parameter of fraction of energy lost by max energy cell in one of T-Card cells
        enabled: true                               # Enable setting these values
        values: {"all" : [-1.1e-03, -1.1e-03, -1.1e-03, 0]}  # Values are energy lost in [ upper/lower cell in same column, upper/lower cell in left or right, left or right cell in same row, 2nd row upper/lower cells]
    inducedEnergyLossFractionWidth:                 # Fraction of energy lost by max energy cell in one of T-Card cells, width of random gaussian
        enabled: true                              # Enable setting these values
        values: {"all" : [5.0e-03,5.0e-03,5.0e-03, 0]}        # Values are energy lost in [ upper/lower cell in same column, upper/lower cell in left or right, left or right cell in same row, ??]
    inducedEnergyLossMinimumFraction:               # Minimum induced energy fraction when linear dependency is set
        enabled: true                               # Enable setting these values
        values: {0 : [3.5e-3], 1 : [5.0e-3], 2 : [4.5e-3], 3 : [6.0e-3], 4 : [3.5e-3], 5 : [3.5e-3], 6 : [3.5e-3], 7 : [6.0e-3], 8 : [3.5e-3], 9 : [3.5e-3], 
                 10: [5.0e-3], 11: [5.0e-3], 12: [3.5e-3], 13: [3.5e-3], 14: [3.5e-3], 15: [3.5e-3], 16: [3.5e-3], 17: [3.5e-3], 18: [3.5e-3], 19: [3.5e-3], 
                 20: [3.5e-3], 21: [3.5e-3]} 
       #values: {"all" : [0.008]}                   # Values are [minimum fraction]
    inducedEnergyLossMaximumFraction:               # Maximum induced energy fraction when linear dependency is set
        enabled: true                               # Enable setting these values
        values: {"all" : [0.018]}                   # Values are [maximum fraction]
    inducedEnergyLossProbability:                   # Fraction of times max cell energy correlates with cross cells
        enabled: true                               # Enable setting these values
        values: {"all" : [1.0]} 
       #values: {0 : [0.30], 1 : [0.60], 2 : [0.50], 3 : [1.00], 4 : [0.35], 5 : [0.25], 6 : [0.35], 7 : [1.00], 8 : [0.25], 9 : [0.25], 
       #         10: [0.35], 11: [0.35], 12: [0.35], 13: [0.35], 14: [0.35], 15: [0.35], 16: [0.35], 17: [0.35], 18: [0.35], 19: [0.35]}  # Values are [probability per event from 0 to 1]

#executionOrder:
#    - CellEmulateCrosstalk
#    - CellEnergy
#    - CellBadChannel
#    - CellTimeCalib
#    - CellCombineCollections
#    - Clusterizer
#    - ClusterExotics
#    - ClusterNonLinearity
#    - ClusterTrackMatcher
#    - ClusterHadronicCorrection
#    - PHOSCorrections

