configurationName: "EMCal Run2 Data Correction Cluster V1"
CellEnergy:
    enabled: true
    createHistos: true
    enableNewTempCalib: true
    enableShaperCorrection: true
CellBadChannel:
    enabled: true
    createHistos: true
CellTimeCalib:
    enabled: true
    createHistos: true
    doCalibrateLowGain: true 
    doCalibTimeEdep: false
Clusterizer:
    enabled: true
    clusterizer: kClusterizerv1
    cellE: 0.1
    seedE: 0.5
    cellTimeMin: -500e-6
    cellTimeMax:  500e-6
    clusterTimeLength: 1e6
    createHistos: true
    recalDistToBadChannels: true
    recalShowerShape: false
ClusterExotics:
    enabled: false          # false since applied in the analysis 
    createHistos: false
    fMaxFcross: 0.95
    fHighEnergyNdiffCut: 50 
ClusterNonLinearity:
    enabled: true
    setForceClusterE: true
    createHistos: true
    nonLinFunct: kTestBeamShaper 
ClusterTrackMatcher:
    enabled: true
    createHistos: true
