configurationName: "PWGGA configuration"
pass: "pass4"
inputObjects:
    cells:
        defaultCells:
            branchName: "usedefault"
    clusterContainers:
        defaultClusterContainer:
            branchName: "usedefault"
        ClusterContainerS500A100:
            branchName: "S500A100ClustersBranch"
        ClusterContainerS500A100W3:
            branchName: "S500A100W3ClustersBranch"
        ClusterContainerS500A100W5:
            branchName: "S500A100W5ClustersBranch"
        ClusterContainerS400A100:
            branchName: "S400A100ClustersBranch"
        ClusterContainerS600A100:
            branchName: "S600A100ClustersBranch"
        ClusterContainerS500A75:
            branchName: "S500A75ClustersBranch"
        ClusterContainerS500A125:
            branchName: "S500A125ClustersBranch"
        ClusterContainerS500A150:
            branchName: "S500A150ClustersBranch"
    trackContainers:
        defaultTrackContainer:
            branchName: "usedefault"
CellEnergy:
    createHistos: true
CellEnergy_defaultSeed:
    enabled: true

CellBadChannel:
    createHistos: true
CellBadChannel_defaultSeed:
    enabled: true

CellTimeCalib:
    createHistos: true
CellTimeCalib_defaultSeed:
    enabled: true

Clusterizer:
    createHistos: true
    clusterizer: kClusterizerv2
    cellTimeMin: -500e-9
    cellTimeMax: +500e-9
    clusterTimeLength: 1e6
    recalDistToBadChannels: true
    remapMcAod: false
    diffEAggregation: 0.0
    cellsNames:
        - defaultCells
Clusterizer_defaultSeed:
    # w0 standard is 4.5
    enabled: true
    cellE: 0.1
    seedE: 0.5
    clusterContainersNames:
        - defaultClusterContainer
Clusterizer_S500A100:
    enabled: true
    cellE: 0.1
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A100
Clusterizer_S500A100W3:
    enabled: true
    cellE: 0.1
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A100W3
Clusterizer_S500A100W5:
    enabled: true
    cellE: 0.1
    seedE: 0.5
    w0: 3
    clusterContainersNames:
        - ClusterContainerS500A100W5
Clusterizer_S400A100:
    enabled: true
    cellE: 0.1
    seedE: 0.4
    w0: 5
    clusterContainersNames:
        - ClusterContainerS400A100
Clusterizer_S600A100:
    enabled: true
    cellE: 0.1
    seedE: 0.6
    clusterContainersNames:
        - ClusterContainerS600A100
Clusterizer_S500A75:
    enabled: true
    cellE: 0.075
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A75
Clusterizer_S500A125:
    enabled: true
    cellE: 0.125
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A125
Clusterizer_S500A150:
    enabled: true
    cellE: 0.15
    seedE: 0.5
    clusterContainersNames:
        - ClusterContainerS500A150

ClusterNonLinearity:
    createHistos: true
    nonLinFunct: kNoCorrection
ClusterNonLinearity_defaultSeed:
    enabled: true
    clusterContainersNames:
        - defaultClusterContainer
ClusterNonLinearity_S500A100:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS500A100
ClusterNonLinearity_S500A100W3:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS500A100W3
ClusterNonLinearity_S500A100W5:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS500A100W5
ClusterNonLinearity_S400A100:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS400A100
ClusterNonLinearity_S600A100:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS600A100
ClusterNonLinearity_S500A75:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS500A75
ClusterNonLinearity_S500A125:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS500A125
ClusterNonLinearity_S500A150:
    enabled: true
    clusterContainersNames:
        - ClusterContainerS500A150
